const KEY='realmforge_v01';
const itemDB={
 'Rusty Sword':{slot:'weapon',class:'warrior',damage:0},'Bronze Sword':{slot:'weapon',class:'warrior',damage:3},'Bronze Dagger':{slot:'weapon',class:'warrior',damage:2,speed:.08},'Bronze Helm':{slot:'head',class:'warrior',damage:1},'Bronze Armour':{slot:'body',class:'warrior',damage:2},
 'Old Shortbow':{slot:'weapon',class:'ranger',damage:0},'Oak Shortbow':{slot:'weapon',class:'ranger',damage:2,range:12},'Leather Hood':{slot:'head',class:'ranger',range:5},'Leather Body':{slot:'body',class:'ranger',damage:1},
 'Cracked Staff':{slot:'weapon',class:'mage',damage:0},'Apprentice Staff':{slot:'weapon',class:'mage',damage:4},'Cloth Hood':{slot:'head',class:'mage',range:5},'Apprentice Robe':{slot:'body',class:'mage',damage:2}
};
const starterEquip=()=>({warrior:{head:'None',body:'Cloth Tunic',weapon:'Rusty Sword'},ranger:{head:'None',body:'Cloth Tunic',weapon:'Old Shortbow'},mage:{head:'None',body:'Cloth Robe',weapon:'Cracked Staff'}});
const base=()=>({coins:0,bestWave:0,skills:{Attack:{lvl:1,xp:0},Strength:{lvl:1,xp:0},Defence:{lvl:1,xp:0},Ranged:{lvl:1,xp:0},Magic:{lvl:1,xp:0},Hitpoints:{lvl:10,xp:0},Mining:{lvl:1,xp:0},Smithing:{lvl:1,xp:0},Woodcutting:{lvl:1,xp:0}},bank:{'Copper ore':0,'Logs':0,'Goblin scrap':0},items:{},equipment:starterEquip(),drops:[]});
let save=JSON.parse(localStorage.getItem(KEY)||'null')||base();
// migrate v0.1 saves without wiping progress
save.items=save.items||{};save.drops=save.drops||[];if(!save.equipment||!save.equipment.warrior)save.equipment=starterEquip();
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');let towers=[],enemies=[],shots=[],selected=null,wave=0,lives=20,battleCoins=100,waveRunning=false,last=0,lastSpawnCheck=0;
const path=[[-30,270],[130,270],[130,120],[350,120],[350,400],[600,400],[600,210],[930,210]];const types={warrior:{cost:40,range:75,damage:10,rate:650,skill:'Attack'},ranger:{cost:55,range:145,damage:8,rate:500,skill:'Ranged'},mage:{cost:70,range:120,damage:17,rate:900,skill:'Magic'}};
function persist(){localStorage.setItem(KEY,JSON.stringify(save));renderUI()}function xpNeed(l){return Math.floor(80*Math.pow(l,1.55))}function addXP(skill,n){let s=save.skills[skill];s.xp+=n;while(s.lvl<99&&s.xp>=xpNeed(s.lvl)){s.xp-=xpNeed(s.lvl);s.lvl++}localStorage.setItem(KEY,JSON.stringify(save))}
function bonus(cls,key){return Object.values(save.equipment[cls]).reduce((n,name)=>n+(itemDB[name]?.[key]||0),0)}
function equipItem(name){let it=itemDB[name];if(!it||!(save.items[name]>0))return;save.equipment[it.class][it.slot]=name;persist()}
window.equipItem=equipItem;
function renderUI(){coins.textContent=save.coins;bestWave.textContent=save.bestWave;skillGrid.innerHTML=Object.entries(save.skills).map(([n,s])=>`<div class="card"><b>${n}</b><div>Level ${s.lvl}</div><small>${s.xp}/${xpNeed(s.lvl)} XP</small><div class="xp"><i style="width:${Math.min(100,s.xp/xpNeed(s.lvl)*100)}%"></i></div></div>`).join('');let resources=Object.entries(save.bank).map(([n,q])=>`<div class="card"><b>${n}</b><div>${q}</div></div>`).join('');let gear=Object.entries(save.items).filter(([,q])=>q>0).map(([n,q])=>{let i=itemDB[n];return `<div class="card"><b>${n}</b><div>Owned: ${q}</div><small>${i.class} • ${i.slot}${i.damage?` • +${i.damage} damage`:''}${i.range?` • +${i.range} range`:''}</small><br><button onclick="equipItem('${n}')">Equip</button></div>`}).join('');bankGrid.innerHTML=resources+gear||'<div class="card">Bank empty</div>';equipmentGrid.innerHTML=['warrior','ranger','mage'].map(c=>`<div class="card"><h3>${c[0].toUpperCase()+c.slice(1)}</h3>${Object.entries(save.equipment[c]).map(([s,n])=>`<div><b>${s}:</b> ${n}</div>`).join('')}<small>Bonus damage +${bonus(c,'damage')} • Range +${bonus(c,'range')}</small></div>`).join('');dropLog.textContent=save.drops.length?save.drops.slice(-5).reverse().join(' • '):'No equipment drops yet.'}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.querySelector('#'+b.dataset.screen).classList.add('active')});document.querySelectorAll('.tower').forEach(b=>b.onclick=()=>{selected=b.dataset.type;document.querySelectorAll('.tower').forEach(x=>x.classList.toggle('selected',x===b))});newGame.onclick=()=>{if(confirm('This permanently resets your Realmforge save. Continue?')&&confirm('Final warning: reset ALL progress?')){save=base();persist();resetBattle()}};
function resetBattle(){towers=[];enemies=[];shots=[];wave=0;lives=20;battleCoins=100;waveRunning=false;hud()}function hud(){document.querySelector('#wave').textContent=wave;document.querySelector('#lives').textContent=lives;document.querySelector('#battleCoins').textContent=battleCoins}function nearRoad(x,y){for(let i=1;i<path.length;i++){let [x1,y1]=path[i-1],[x2,y2]=path[i],dx=x2-x1,dy=y2-y1,t=Math.max(0,Math.min(1,((x-x1)*dx+(y-y1)*dy)/(dx*dx+dy*dy)));if(Math.hypot(x-(x1+t*dx),y-(y1+t*dy))<38)return true}return false}
canvas.addEventListener('pointerdown',e=>{if(!selected)return;let r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*canvas.width/r.width,y=(e.clientY-r.top)*canvas.height/r.height,t=types[selected];if(battleCoins<t.cost||nearRoad(x,y)||towers.some(a=>Math.hypot(a.x-x,a.y-y)<45))return;battleCoins-=t.cost;towers.push({x,y,type:selected,last:0});hud()});
startWave.onclick=()=>{if(waveRunning||wave>=10)return;wave++;waveRunning=true;lastSpawnCheck=performance.now();let count=5+wave*2;for(let i=0;i<count;i++)setTimeout(()=>spawn(i%4===3?'goblin':'rat'),i*650);hud()};function spawn(kind){let hp=(kind==='rat'?25:45)*(1+wave*.16);enemies.push({kind,x:path[0][0],y:path[0][1],seg:1,hp,max:hp,speed:kind==='rat'?55:42,reward:kind==='rat'?5:8,dead:false})}
function rollDrop(kind){let pool=kind==='goblin'?[['Bronze Sword',.025],['Bronze Dagger',.02],['Bronze Helm',.018],['Bronze Armour',.012],['Oak Shortbow',.018],['Leather Hood',.016],['Leather Body',.012],['Apprentice Staff',.012],['Cloth Hood',.014],['Apprentice Robe',.01]]:[['Bronze Dagger',.004],['Leather Hood',.003],['Cloth Hood',.003]];for(const [name,chance] of pool)if(Math.random()<chance){save.items[name]=(save.items[name]||0)+1;save.drops.push(`${name} drop!`);if(save.drops.length>20)save.drops.shift();return}}
function update(dt,now){for(const e of enemies){if(e.dead)continue;let p=path[e.seg];if(!p){e.dead=true;lives--;continue}let dx=p[0]-e.x,dy=p[1]-e.y,d=Math.hypot(dx,dy),step=e.speed*dt;if(d<=step){e.x=p[0];e.y=p[1];e.seg++}else{e.x+=dx/d*step;e.y+=dy/d*step}}for(const t of towers){let cfg=types[t.type],range=cfg.range+bonus(t.type,'range'),target=enemies.find(e=>!e.dead&&Math.hypot(e.x-t.x,e.y-t.y)<=range),rate=cfg.rate*(1-bonus(t.type,'speed'));if(target&&now-t.last>=rate){t.last=now;let level=save.skills[cfg.skill].lvl,damage=(cfg.damage+bonus(t.type,'damage'))*(1+(level-1)*.025);target.hp-=damage;shots.push({x:t.x,y:t.y,tx:target.x,ty:target.y,life:.12});addXP(cfg.skill,2);if(target.hp<=0&&!target.dead){target.dead=true;battleCoins+=target.reward;save.coins+=target.reward;if(target.kind==='goblin')save.bank['Goblin scrap']++;if(Math.random()<.18)save.bank['Copper ore']++;rollDrop(target.kind);persist();hud()}}}shots.forEach(s=>s.life-=dt);shots=shots.filter(s=>s.life>0);enemies=enemies.filter(e=>!e.dead);if(waveRunning&&enemies.length===0){let expected=5+wave*2;if(now-lastSpawnCheck>expected*650+500){waveRunning=false;save.bestWave=Math.max(save.bestWave,wave);persist()}}if(lives<=0){alert('Defence failed. Your account XP and loot are saved.');resetBattle()}}
function draw(){ctx.clearRect(0,0,900,520);ctx.fillStyle='#6f8757';ctx.fillRect(0,0,900,520);ctx.strokeStyle='#8d7555';ctx.lineWidth=55;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();path.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.stroke();ctx.fillStyle='#3c4b31';for(let i=0;i<18;i++)ctx.fillRect((i*137)%880,(i*83)%500,8,8);towers.forEach(t=>{ctx.beginPath();ctx.fillStyle=t.type==='warrior'?'#777':t.type==='ranger'?'#385f35':'#60477b';ctx.arc(t.x,t.y,18,0,Math.PI*2);ctx.fill();ctx.fillStyle='white';ctx.font='12px sans-serif';ctx.textAlign='center';ctx.fillText(t.type[0].toUpperCase(),t.x,t.y+4)});enemies.forEach(e=>{ctx.beginPath();ctx.fillStyle=e.kind==='rat'?'#5b514c':'#4e7338';ctx.arc(e.x,e.y,13,0,Math.PI*2);ctx.fill();ctx.fillStyle='#222';ctx.fillRect(e.x-15,e.y-22,30,4);ctx.fillStyle='#ddd';ctx.fillRect(e.x-15,e.y-22,30*(e.hp/e.max),4)});ctx.strokeStyle='#f4dd79';ctx.lineWidth=3;shots.forEach(s=>{ctx.beginPath();ctx.moveTo(s.x,s.y);ctx.lineTo(s.tx,s.ty);ctx.stroke()})}function loop(now){let dt=Math.min(.04,(now-last)/1000||0);last=now;update(dt,now);draw();requestAnimationFrame(loop)}renderUI();hud();persist();requestAnimationFrame(loop);